/* tslint:disable */
/* eslint-disable */
/**
 * shopping-cart Api Documentation
 * shopping-cart Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@shopping_cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AddCart
 */
export interface AddCart {
    /**
     * User Id
     * @type {string}
     * @memberof AddCart
     */
    userId?: string;
    /**
     * Variant Id
     * @type {string}
     * @memberof AddCart
     */
    variantId?: string;
    /**
     * Quantity
     * @type {string}
     * @memberof AddCart
     */
    quantity?: string;
}

/**
 * Check if a given object implements the AddCart interface.
 */
export function instanceOfAddCart(value: object): value is AddCart {
    return true;
}

export function AddCartFromJSON(json: any): AddCart {
    return AddCartFromJSONTyped(json, false);
}

export function AddCartFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddCart {
    if (json == null) {
        return json;
    }
    return {

        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'variantId': json['variant_id'] == null ? undefined : json['variant_id'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function AddCartToJSON(json: any): AddCart {
    return AddCartToJSONTyped(json, false);
}

export function AddCartToJSONTyped(value?: AddCart | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'user_id': value['userId'],
        'variant_id': value['variantId'],
        'quantity': value['quantity'],
    };
}
