/* tslint:disable */
/* eslint-disable */
/**
 * shopping-cart Api Documentation
 * shopping-cart Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@shopping_cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AddOrders
 */
export interface AddOrders {
    /**
     * User Id
     * @type {string}
     * @memberof AddOrders
     */
    userId?: string;
    /**
     * Order Date
     * @type {string}
     * @memberof AddOrders
     */
    orderDate?: string;
    /**
     * Total
     * @type {string}
     * @memberof AddOrders
     */
    total?: string;
}

/**
 * Check if a given object implements the AddOrders interface.
 */
export function instanceOfAddOrders(value: object): value is AddOrders {
    return true;
}

export function AddOrdersFromJSON(json: any): AddOrders {
    return AddOrdersFromJSONTyped(json, false);
}

export function AddOrdersFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddOrders {
    if (json == null) {
        return json;
    }
    return {

        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'orderDate': json['order_date'] == null ? undefined : json['order_date'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function AddOrdersToJSON(json: any): AddOrders {
    return AddOrdersToJSONTyped(json, false);
}

export function AddOrdersToJSONTyped(value?: AddOrders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'user_id': value['userId'],
        'order_date': value['orderDate'],
        'total': value['total'],
    };
}
