/* tslint:disable */
/* eslint-disable */
/**
 * shopping-cart Api Documentation
 * shopping-cart Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@shopping_cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AddUsers
 */
export interface AddUsers {
    /**
     * Username
     * @type {string}
     * @memberof AddUsers
     */
    username?: string;
    /**
     * Email
     * @type {string}
     * @memberof AddUsers
     */
    email?: string;
    /**
     * Password
     * @type {string}
     * @memberof AddUsers
     */
    password?: string;
    /**
     * Name
     * @type {string}
     * @memberof AddUsers
     */
    name?: string;
    /**
     * Phone
     * @type {string}
     * @memberof AddUsers
     */
    phone?: string;
    /**
     * Address
     * @type {string}
     * @memberof AddUsers
     */
    address?: string;
    /**
     * Image Url
     * @type {string}
     * @memberof AddUsers
     */
    imageUrl?: string;
}

/**
 * Check if a given object implements the AddUsers interface.
 */
export function instanceOfAddUsers(value: object): value is AddUsers {
    return true;
}

export function AddUsersFromJSON(json: any): AddUsers {
    return AddUsersFromJSONTyped(json, false);
}

export function AddUsersFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUsers {
    if (json == null) {
        return json;
    }
    return {

        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'name': json['name'] == null ? undefined : json['name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'address': json['address'] == null ? undefined : json['address'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
    };
}

export function AddUsersToJSON(json: any): AddUsers {
    return AddUsersToJSONTyped(json, false);
}

export function AddUsersToJSONTyped(value?: AddUsers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'username': value['username'],
        'email': value['email'],
        'password': value['password'],
        'name': value['name'],
        'phone': value['phone'],
        'address': value['address'],
        'image_url': value['imageUrl'],
    };
}
