/* tslint:disable */
/* eslint-disable */
/**
 * shopping-cart Api Documentation
 * shopping-cart Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@shopping_cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EditOrders
 */
export interface EditOrders {
    /**
     * User Id
     * @type {string}
     * @memberof EditOrders
     */
    userId?: string;
    /**
     * Order Date
     * @type {string}
     * @memberof EditOrders
     */
    orderDate?: string;
    /**
     * Total
     * @type {string}
     * @memberof EditOrders
     */
    total?: string;
}

/**
 * Check if a given object implements the EditOrders interface.
 */
export function instanceOfEditOrders(value: object): value is EditOrders {
    return true;
}

export function EditOrdersFromJSON(json: any): EditOrders {
    return EditOrdersFromJSONTyped(json, false);
}

export function EditOrdersFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditOrders {
    if (json == null) {
        return json;
    }
    return {

        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'orderDate': json['order_date'] == null ? undefined : json['order_date'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function EditOrdersToJSON(json: any): EditOrders {
    return EditOrdersToJSONTyped(json, false);
}

export function EditOrdersToJSONTyped(value?: EditOrders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'user_id': value['userId'],
        'order_date': value['orderDate'],
        'total': value['total'],
    };
}
