/* tslint:disable */
/* eslint-disable */
/**
 * shopping-cart Api Documentation
 * shopping-cart Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@shopping_cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EditCart
 */
export interface EditCart {
    /**
     * User Id
     * @type {string}
     * @memberof EditCart
     */
    userId?: string;
    /**
     * Variant Id
     * @type {string}
     * @memberof EditCart
     */
    variantId?: string;
    /**
     * Quantity
     * @type {string}
     * @memberof EditCart
     */
    quantity?: string;
}

/**
 * Check if a given object implements the EditCart interface.
 */
export function instanceOfEditCart(value: object): value is EditCart {
    return true;
}

export function EditCartFromJSON(json: any): EditCart {
    return EditCartFromJSONTyped(json, false);
}

export function EditCartFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditCart {
    if (json == null) {
        return json;
    }
    return {

        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'variantId': json['variant_id'] == null ? undefined : json['variant_id'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function EditCartToJSON(json: any): EditCart {
    return EditCartToJSONTyped(json, false);
}

export function EditCartToJSONTyped(value?: EditCart | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'user_id': value['userId'],
        'variant_id': value['variantId'],
        'quantity': value['quantity'],
    };
}
