/* tslint:disable */
/* eslint-disable */
/**
 * shopping-cart Api Documentation
 * shopping-cart Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@shopping_cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EditProducts
 */
export interface EditProducts {
    /**
     * Name
     * @type {string}
     * @memberof EditProducts
     */
    name?: string;
    /**
     * Description
     * @type {string}
     * @memberof EditProducts
     */
    description?: string;
    /**
     * Price
     * @type {string}
     * @memberof EditProducts
     */
    price?: string;
    /**
     * Category
     * @type {string}
     * @memberof EditProducts
     */
    category?: string;
    /**
     * Stock
     * @type {string}
     * @memberof EditProducts
     */
    stock?: string;
    /**
     * Image Url
     * @type {string}
     * @memberof EditProducts
     */
    imageUrl?: string;
}

/**
 * Check if a given object implements the EditProducts interface.
 */
export function instanceOfEditProducts(value: object): value is EditProducts {
    return true;
}

export function EditProductsFromJSON(json: any): EditProducts {
    return EditProductsFromJSONTyped(json, false);
}

export function EditProductsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditProducts {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
        'category': json['category'] == null ? undefined : json['category'],
        'stock': json['stock'] == null ? undefined : json['stock'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
    };
}

export function EditProductsToJSON(json: any): EditProducts {
    return EditProductsToJSONTyped(json, false);
}

export function EditProductsToJSONTyped(value?: EditProducts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'name': value['name'],
        'description': value['description'],
        'price': value['price'],
        'category': value['category'],
        'stock': value['stock'],
        'image_url': value['imageUrl'],
    };
}
