/* tslint:disable */
/* eslint-disable */
/**
 * shopping-cart Api Documentation
 * shopping-cart Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@shopping_cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EditUsers
 */
export interface EditUsers {
    /**
     * Username
     * @type {string}
     * @memberof EditUsers
     */
    username?: string;
    /**
     * Email
     * @type {string}
     * @memberof EditUsers
     */
    email?: string;
    /**
     * Name
     * @type {string}
     * @memberof EditUsers
     */
    name?: string;
    /**
     * Phone
     * @type {string}
     * @memberof EditUsers
     */
    phone?: string;
    /**
     * Address
     * @type {string}
     * @memberof EditUsers
     */
    address?: string;
    /**
     * Image Url
     * @type {string}
     * @memberof EditUsers
     */
    imageUrl?: string;
}

/**
 * Check if a given object implements the EditUsers interface.
 */
export function instanceOfEditUsers(value: object): value is EditUsers {
    return true;
}

export function EditUsersFromJSON(json: any): EditUsers {
    return EditUsersFromJSONTyped(json, false);
}

export function EditUsersFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditUsers {
    if (json == null) {
        return json;
    }
    return {

        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'address': json['address'] == null ? undefined : json['address'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
    };
}

export function EditUsersToJSON(json: any): EditUsers {
    return EditUsersToJSONTyped(json, false);
}

export function EditUsersToJSONTyped(value?: EditUsers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'username': value['username'],
        'email': value['email'],
        'name': value['name'],
        'phone': value['phone'],
        'address': value['address'],
        'image_url': value['imageUrl'],
    };
}
