/* tslint:disable */
/* eslint-disable */
/**
 * shopping-cart Api Documentation
 * shopping-cart Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@shopping_cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ListProducts
 */
export interface ListProducts {
    /**
     * Id
     * @type {string}
     * @memberof ListProducts
     */
    id?: string;
    /**
     * Name
     * @type {string}
     * @memberof ListProducts
     */
    name?: string;
    /**
     * Description
     * @type {string}
     * @memberof ListProducts
     */
    description?: string;
    /**
     * Price
     * @type {string}
     * @memberof ListProducts
     */
    price?: string;
    /**
     * Category
     * @type {string}
     * @memberof ListProducts
     */
    category?: string;
    /**
     * Stock
     * @type {string}
     * @memberof ListProducts
     */
    stock?: string;
    /**
     * Image Url
     * @type {string}
     * @memberof ListProducts
     */
    imageUrl?: string;
}

/**
 * Check if a given object implements the ListProducts interface.
 */
export function instanceOfListProducts(value: object): value is ListProducts {
    return true;
}

export function ListProductsFromJSON(json: any): ListProducts {
    return ListProductsFromJSONTyped(json, false);
}

export function ListProductsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProducts {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
        'category': json['category'] == null ? undefined : json['category'],
        'stock': json['stock'] == null ? undefined : json['stock'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
    };
}

export function ListProductsToJSON(json: any): ListProducts {
    return ListProductsToJSONTyped(json, false);
}

export function ListProductsToJSONTyped(value?: ListProducts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'price': value['price'],
        'category': value['category'],
        'stock': value['stock'],
        'image_url': value['imageUrl'],
    };
}
