/* tslint:disable */
/* eslint-disable */
/**
 * shopping-cart Api Documentation
 * shopping-cart Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@shopping_cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ListUsers
 */
export interface ListUsers {
    /**
     * Id
     * @type {string}
     * @memberof ListUsers
     */
    id?: string;
    /**
     * Username
     * @type {string}
     * @memberof ListUsers
     */
    username?: string;
    /**
     * Email
     * @type {string}
     * @memberof ListUsers
     */
    email?: string;
    /**
     * Name
     * @type {string}
     * @memberof ListUsers
     */
    name?: string;
    /**
     * Phone
     * @type {string}
     * @memberof ListUsers
     */
    phone?: string;
    /**
     * Address
     * @type {string}
     * @memberof ListUsers
     */
    address?: string;
    /**
     * Image Url
     * @type {string}
     * @memberof ListUsers
     */
    imageUrl?: string;
}

/**
 * Check if a given object implements the ListUsers interface.
 */
export function instanceOfListUsers(value: object): value is ListUsers {
    return true;
}

export function ListUsersFromJSON(json: any): ListUsers {
    return ListUsersFromJSONTyped(json, false);
}

export function ListUsersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListUsers {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'address': json['address'] == null ? undefined : json['address'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
    };
}

export function ListUsersToJSON(json: any): ListUsers {
    return ListUsersToJSONTyped(json, false);
}

export function ListUsersToJSONTyped(value?: ListUsers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
        'name': value['name'],
        'phone': value['phone'],
        'address': value['address'],
        'image_url': value['imageUrl'],
    };
}
