/* tslint:disable */
/* eslint-disable */
/**
 * shopping-cart Api Documentation
 * shopping-cart Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@shopping_cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ListOrders
 */
export interface ListOrders {
    /**
     * Id
     * @type {string}
     * @memberof ListOrders
     */
    id?: string;
    /**
     * User Id
     * @type {string}
     * @memberof ListOrders
     */
    userId?: string;
    /**
     * Order Date
     * @type {string}
     * @memberof ListOrders
     */
    orderDate?: string;
    /**
     * Total
     * @type {string}
     * @memberof ListOrders
     */
    total?: string;
}

/**
 * Check if a given object implements the ListOrders interface.
 */
export function instanceOfListOrders(value: object): value is ListOrders {
    return true;
}

export function ListOrdersFromJSON(json: any): ListOrders {
    return ListOrdersFromJSONTyped(json, false);
}

export function ListOrdersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrders {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'orderDate': json['order_date'] == null ? undefined : json['order_date'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ListOrdersToJSON(json: any): ListOrders {
    return ListOrdersToJSONTyped(json, false);
}

export function ListOrdersToJSONTyped(value?: ListOrders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'user_id': value['userId'],
        'order_date': value['orderDate'],
        'total': value['total'],
    };
}
