/* tslint:disable */
/* eslint-disable */
/**
 * shopping-cart Api Documentation
 * shopping-cart Api Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@shopping_cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ViewUsers
 */
export interface ViewUsers {
    /**
     * Id
     * @type {string}
     * @memberof ViewUsers
     */
    id?: string;
    /**
     * Username
     * @type {string}
     * @memberof ViewUsers
     */
    username?: string;
    /**
     * Email
     * @type {string}
     * @memberof ViewUsers
     */
    email?: string;
    /**
     * Name
     * @type {string}
     * @memberof ViewUsers
     */
    name?: string;
    /**
     * Phone
     * @type {string}
     * @memberof ViewUsers
     */
    phone?: string;
    /**
     * Address
     * @type {string}
     * @memberof ViewUsers
     */
    address?: string;
    /**
     * Image Url
     * @type {string}
     * @memberof ViewUsers
     */
    imageUrl?: string;
}

/**
 * Check if a given object implements the ViewUsers interface.
 */
export function instanceOfViewUsers(value: object): value is ViewUsers {
    return true;
}

export function ViewUsersFromJSON(json: any): ViewUsers {
    return ViewUsersFromJSONTyped(json, false);
}

export function ViewUsersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewUsers {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'address': json['address'] == null ? undefined : json['address'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
    };
}

export function ViewUsersToJSON(json: any): ViewUsers {
    return ViewUsersToJSONTyped(json, false);
}

export function ViewUsersToJSONTyped(value?: ViewUsers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
        'name': value['name'],
        'phone': value['phone'],
        'address': value['address'],
        'image_url': value['imageUrl'],
    };
}
